name: Hugo Build and Status Check

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - master

jobs:
  build:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    # Steps to be executed as part of the job
    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step to set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Always use the latest version of Hugo, in case of issue with the latest version, 
          # you can specify a specific version using '0.125.5'
          hugo-version: 'latest'
          # Set the extended option to true to install the extended version of Hugo, mandatory for Microcks website
          extended: true

      # Step to start Hugo --minify to validate site and build process
      - name: Start Hugo
        run: hugo server --minify

      # Add other steps here

      # Step to check build status and block commit if build fails
      - name: Check build status
        run: |
          if [ $? -ne 0 ]; then
            echo "::error Hugo build failed, ::blocking commit..."
            exit 1
          fi

      # Optionally, add a step to stop the Hugo server at the end of the workflow
      #- name: Stop Hugo server
      #  run: kill $(lsof -t -i:8888) || true
